### ISSUE TITLE
Bug: Static assets are also pre-processed causing errors

### ISSUE THREAD

**Issue by Cayllen** [bluwy/svelte-preprocess-import-assets#19]
Following issue:
- I have some svg's in my static folder static/features. As of my knowledge static images should not be processed, why is this still happening?
- The first image works without issues
- The second image does not work and gives me an error. Only when using` <!-- svelte-preprocess-import-assets-ignore -->`
 it works.

```js
<script> 
	let varName = myimage.svg
</script>

<img src="features/{image}" alt="illustration related to the feature description" />

<img src="features/waves.svg" alt="illustration related to the feature description" />
```

The error:
```
[plugin:vite:import-analysis] Failed to resolve import "features/waves.svg" from "src/routes/components/Feature.svelte". Does the file exist?
/Users/..../Desktop/Code/VSCode/myWebsite/src/routes/components/Feature.svelte:27:27
25 |  } from "svelte/internal";
26 |  
27 |  import ___ASSET___0 from "features/waves.svg";
   |                            ^
28 |  import { reveal } from 'svelte-reveal';
29 |  const file = "src/routes/components/Feature.svelte";
```

**Comment by bluwy** [comment]
The preprocessor works file-by-file without knowledge of what are static and what aren't, so by default it assumes all to be imported if it's a static-string. The first case worked because it has dynamic variables, so it isn't a static-string..

If you want to ignore a "static-string" `src` that links to a static folder, you can configure the `urlFilter` option to return false if it starts with `features` or `/features` etc.
