### ISSUE TITLE
vite-imagetools

### ISSUE THREAD

**Issue by nosovk** [bluwy/svelte-preprocess-import-assets#3]
It would be nice to have some sort of config, that will allow to seamlessly integrate with vite-imagetools.
For example to fill srcset property instead of src.

Or to pass vite-imagetools meta to some svelte component as props.

**Comment by bluwy** [comment]
> For example to fill srcset property instead of src.

The preprocessor already parses `srcset` for any link to images. Would that be enough for imagetools integration?

> Or to pass vite-imagetools meta to some svelte component as props.

I've also thought about some sort of config that works on component props. Should be doable with a bit of tweaking. But I wonder if we would need that if we have a `svelte-imagetools` (which I haven't had time to work on).

Otherwise if you have an idea of the ideal usage syntax, it would help to figure out what needs to be done to support it.

**Comment by bluwy** [comment]
Closing this as I think it's better to have a separate `svelte-imagetools` package to tackle this, to also reduce the scope of the package right now. Perhaps if the API can be converged at some point, we can consider having support for it too.
